# Generated by Django 4.2.4 on 2023-12-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
                ('age', models.IntegerField()),
                ('mobile_no', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('city', models.TextField(max_length=100)),
                ('state', models.TextField(max_length=100)),
            ],
        ),
    ]
