# Generated by Django 4.2.4 on 2023-12-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_file_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='age',
            field=models.TextField(max_length=100),
        ),
    ]
