# Generated by Django 4.2.4 on 2023-12-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_file_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='roll_no',
            field=models.TextField(max_length=100),
        ),
    ]
