# Generated by Django 4.2.4 on 2023-12-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_file_roll_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fathers_name', models.TextField(max_length=100)),
                ('f_mobile', models.TextField(max_length=100)),
                ('f_email', models.TextField(max_length=100)),
                ('f_age', models.IntegerField()),
            ],
        ),
    ]
