# Generated by Django 4.2.4 on 2023-12-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
