# Generated by Django 4.2.4 on 2023-12-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_additionalinfo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='f_mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='file',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='file',
            name='roll_no',
            field=models.IntegerField(),
        ),
    ]
